package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.ads.internal.util.client.VersionInfoParcel;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* loaded from: classes.dex */
public final class zzbyz extends u2.a {
    public static final Parcelable.Creator<zzbyz> CREATOR = new zzbza();
    public final long zzA;
    public final String zzB;
    public final float zzC;
    public final int zzD;
    public final int zzE;
    public final boolean zzF;
    public final String zzG;
    public final boolean zzH;
    public final String zzI;
    public final boolean zzJ;
    public final int zzK;
    public final Bundle zzL;
    public final String zzM;
    public final com.google.android.gms.ads.internal.client.zzeh zzN;
    public final boolean zzO;
    public final Bundle zzP;
    public final String zzQ;
    public final String zzR;
    public final String zzS;
    public final boolean zzT;
    public final List zzU;
    public final String zzV;
    public final List zzW;
    public final int zzX;
    public final boolean zzY;
    public final boolean zzZ;
    public final int zza;
    public final boolean zzaa;
    public final ArrayList zzab;
    public final String zzac;
    public final zzbqs zzad;
    public final String zzae;
    public final Bundle zzaf;
    public final Bundle zzb;
    public final com.google.android.gms.ads.internal.client.zzm zzc;
    public final com.google.android.gms.ads.internal.client.zzr zzd;
    public final String zze;
    public final ApplicationInfo zzf;
    public final PackageInfo zzg;
    public final String zzh;
    public final String zzi;
    public final String zzj;
    public final VersionInfoParcel zzk;
    public final Bundle zzl;
    public final int zzm;
    public final List zzn;
    public final Bundle zzo;
    public final boolean zzp;
    public final int zzq;
    public final int zzr;
    public final float zzs;
    public final String zzt;
    public final long zzu;
    public final String zzv;
    public final List zzw;
    public final String zzx;
    public final zzbkh zzy;
    public final List zzz;

    public zzbyz(int i5, Bundle bundle, com.google.android.gms.ads.internal.client.zzm zzmVar, com.google.android.gms.ads.internal.client.zzr zzrVar, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, VersionInfoParcel versionInfoParcel, Bundle bundle2, int i6, List list, Bundle bundle3, boolean z4, int i7, int i8, float f5, String str5, long j2, String str6, List list2, String str7, zzbkh zzbkhVar, List list3, long j5, String str8, float f6, boolean z5, int i9, int i10, boolean z6, String str9, String str10, boolean z7, int i11, Bundle bundle4, String str11, com.google.android.gms.ads.internal.client.zzeh zzehVar, boolean z8, Bundle bundle5, String str12, String str13, String str14, boolean z9, List list4, String str15, List list5, int i12, boolean z10, boolean z11, boolean z12, ArrayList arrayList, String str16, zzbqs zzbqsVar, String str17, Bundle bundle6) {
        this.zza = i5;
        this.zzb = bundle;
        this.zzc = zzmVar;
        this.zzd = zzrVar;
        this.zze = str;
        this.zzf = applicationInfo;
        this.zzg = packageInfo;
        this.zzh = str2;
        this.zzi = str3;
        this.zzj = str4;
        this.zzk = versionInfoParcel;
        this.zzl = bundle2;
        this.zzm = i6;
        this.zzn = list;
        this.zzz = list3 == null ? Collections.EMPTY_LIST : Collections.unmodifiableList(list3);
        this.zzo = bundle3;
        this.zzp = z4;
        this.zzq = i7;
        this.zzr = i8;
        this.zzs = f5;
        this.zzt = str5;
        this.zzu = j2;
        this.zzv = str6;
        this.zzw = list2 == null ? Collections.EMPTY_LIST : Collections.unmodifiableList(list2);
        this.zzx = str7;
        this.zzy = zzbkhVar;
        this.zzA = j5;
        this.zzB = str8;
        this.zzC = f6;
        this.zzH = z5;
        this.zzD = i9;
        this.zzE = i10;
        this.zzF = z6;
        this.zzG = str9;
        this.zzI = str10;
        this.zzJ = z7;
        this.zzK = i11;
        this.zzL = bundle4;
        this.zzM = str11;
        this.zzN = zzehVar;
        this.zzO = z8;
        this.zzP = bundle5;
        this.zzQ = str12;
        this.zzR = str13;
        this.zzS = str14;
        this.zzT = z9;
        this.zzU = list4;
        this.zzV = str15;
        this.zzW = list5;
        this.zzX = i12;
        this.zzY = z10;
        this.zzZ = z11;
        this.zzaa = z12;
        this.zzab = arrayList;
        this.zzac = str16;
        this.zzad = zzbqsVar;
        this.zzae = str17;
        this.zzaf = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i5) {
        int i6 = this.zza;
        int O = z2.b.O(parcel, 20293);
        z2.b.N(parcel, 1, 4);
        parcel.writeInt(i6);
        z2.b.E(parcel, 2, this.zzb);
        z2.b.H(parcel, 3, this.zzc, i5);
        z2.b.H(parcel, 4, this.zzd, i5);
        z2.b.I(parcel, 5, this.zze);
        z2.b.H(parcel, 6, this.zzf, i5);
        z2.b.H(parcel, 7, this.zzg, i5);
        z2.b.I(parcel, 8, this.zzh);
        z2.b.I(parcel, 9, this.zzi);
        z2.b.I(parcel, 10, this.zzj);
        z2.b.H(parcel, 11, this.zzk, i5);
        z2.b.E(parcel, 12, this.zzl);
        int i7 = this.zzm;
        z2.b.N(parcel, 13, 4);
        parcel.writeInt(i7);
        z2.b.K(parcel, 14, this.zzn);
        z2.b.E(parcel, 15, this.zzo);
        boolean z4 = this.zzp;
        z2.b.N(parcel, 16, 4);
        parcel.writeInt(z4 ? 1 : 0);
        int i8 = this.zzq;
        z2.b.N(parcel, 18, 4);
        parcel.writeInt(i8);
        int i9 = this.zzr;
        z2.b.N(parcel, 19, 4);
        parcel.writeInt(i9);
        float f5 = this.zzs;
        z2.b.N(parcel, 20, 4);
        parcel.writeFloat(f5);
        z2.b.I(parcel, 21, this.zzt);
        long j2 = this.zzu;
        z2.b.N(parcel, 25, 8);
        parcel.writeLong(j2);
        z2.b.I(parcel, 26, this.zzv);
        z2.b.K(parcel, 27, this.zzw);
        z2.b.I(parcel, 28, this.zzx);
        z2.b.H(parcel, 29, this.zzy, i5);
        z2.b.K(parcel, 30, this.zzz);
        long j5 = this.zzA;
        z2.b.N(parcel, 31, 8);
        parcel.writeLong(j5);
        z2.b.I(parcel, 33, this.zzB);
        float f6 = this.zzC;
        z2.b.N(parcel, 34, 4);
        parcel.writeFloat(f6);
        int i10 = this.zzD;
        z2.b.N(parcel, 35, 4);
        parcel.writeInt(i10);
        int i11 = this.zzE;
        z2.b.N(parcel, 36, 4);
        parcel.writeInt(i11);
        boolean z5 = this.zzF;
        z2.b.N(parcel, 37, 4);
        parcel.writeInt(z5 ? 1 : 0);
        z2.b.I(parcel, 39, this.zzG);
        boolean z6 = this.zzH;
        z2.b.N(parcel, 40, 4);
        parcel.writeInt(z6 ? 1 : 0);
        z2.b.I(parcel, 41, this.zzI);
        boolean z7 = this.zzJ;
        z2.b.N(parcel, 42, 4);
        parcel.writeInt(z7 ? 1 : 0);
        int i12 = this.zzK;
        z2.b.N(parcel, 43, 4);
        parcel.writeInt(i12);
        z2.b.E(parcel, 44, this.zzL);
        z2.b.I(parcel, 45, this.zzM);
        z2.b.H(parcel, 46, this.zzN, i5);
        boolean z8 = this.zzO;
        z2.b.N(parcel, 47, 4);
        parcel.writeInt(z8 ? 1 : 0);
        z2.b.E(parcel, 48, this.zzP);
        z2.b.I(parcel, 49, this.zzQ);
        z2.b.I(parcel, 50, this.zzR);
        z2.b.I(parcel, 51, this.zzS);
        boolean z9 = this.zzT;
        z2.b.N(parcel, 52, 4);
        parcel.writeInt(z9 ? 1 : 0);
        List list = this.zzU;
        if (list != null) {
            int O2 = z2.b.O(parcel, 53);
            int size = list.size();
            parcel.writeInt(size);
            for (int i13 = 0; i13 < size; i13++) {
                parcel.writeInt(((Integer) list.get(i13)).intValue());
            }
            z2.b.P(parcel, O2);
        }
        z2.b.I(parcel, 54, this.zzV);
        z2.b.K(parcel, 55, this.zzW);
        int i14 = this.zzX;
        z2.b.N(parcel, 56, 4);
        parcel.writeInt(i14);
        boolean z10 = this.zzY;
        z2.b.N(parcel, 57, 4);
        parcel.writeInt(z10 ? 1 : 0);
        boolean z11 = this.zzZ;
        z2.b.N(parcel, 58, 4);
        parcel.writeInt(z11 ? 1 : 0);
        boolean z12 = this.zzaa;
        z2.b.N(parcel, 59, 4);
        parcel.writeInt(z12 ? 1 : 0);
        z2.b.K(parcel, 60, this.zzab);
        z2.b.I(parcel, 61, this.zzac);
        z2.b.H(parcel, 63, this.zzad, i5);
        z2.b.I(parcel, 64, this.zzae);
        z2.b.E(parcel, 65, this.zzaf);
        z2.b.P(parcel, O);
    }
}
