package com.google.android.gms.internal.ads;

import android.app.Activity;
import android.content.Context;
import android.view.View;
import java.util.Map;

/* loaded from: classes.dex */
final class zzgbv implements zzgfc {
    private final zzgbl zzA;
    private final zzgbr zzB;
    final zzikp zza;
    final zzikp zzb;
    final zzikp zzc;
    final zzikp zzd;
    final zzikp zze;
    final zzikp zzf;
    final zzikp zzg;
    final zzikp zzh;
    final zzikp zzi;
    final zzikp zzj;
    final zzikp zzk;
    final zzikp zzl;
    final zzikp zzm;
    final zzikp zzn;
    final zzikp zzo;
    final zzikp zzp;
    final zzikp zzq;
    final zzikp zzr;
    final zzikp zzs;
    final zzikp zzt;
    final zzikp zzu;
    final zzikp zzv;
    final zzikp zzw;
    final zzikp zzx;
    final zzikp zzy;
    final zzikp zzz;

    public zzgbv(zzgbl zzgblVar, zzgbr zzgbrVar, Context context, View view, Activity activity, String str, Map map, zzawg zzawgVar, zzgcc zzgccVar) {
        this.zzA = zzgblVar;
        this.zzB = zzgbrVar;
        zzikg zza = zzikh.zza(zzgccVar);
        this.zza = zza;
        zzikg zzc = zzikh.zzc(str);
        this.zzb = zzc;
        zzikg zza2 = zzikh.zza(zzawgVar);
        this.zzc = zza2;
        zzikp zzikpVar = zzgbrVar.zzb;
        zzikp zzikpVar2 = zzgblVar.zza;
        zzikp zzikpVar3 = zzgblVar.zzu;
        zzggn zza3 = zzggn.zza(zza2, zzikpVar, zzikpVar2, zzikpVar3);
        this.zzd = zza3;
        zzggl zza4 = zzggl.zza(zza2, zzikpVar, zzikpVar3);
        this.zze = zza4;
        zzikg zza5 = zzikh.zza(map);
        this.zzf = zza5;
        zzikp zzikpVar4 = zzgbrVar.zzb;
        zzikp zzikpVar5 = zzgblVar.zzu;
        zzggt zza6 = zzggt.zza(zza2, zzikpVar4, zza5, zzikpVar5);
        this.zzg = zza6;
        zzggp zza7 = zzggp.zza(zza2, zzikpVar4, zzgblVar.zzj, zzikpVar5);
        this.zzh = zza7;
        zzghd zza8 = zzghd.zza(zza2, zzikpVar4, zza, zza5, zzikpVar5);
        this.zzi = zza8;
        zzggr zza9 = zzggr.zza(zza2, zzikpVar4, zzikpVar5);
        this.zzj = zza9;
        zzikg zza10 = zzikh.zza(context);
        this.zzk = zza10;
        zzikp zzikpVar6 = zzgbrVar.zzb;
        zzikp zzikpVar7 = zzgblVar.zzu;
        zzggz zza11 = zzggz.zza(zza2, zzikpVar6, zza, zza10, zza5, zzikpVar7);
        this.zzl = zza11;
        zzikp zzikpVar8 = zzgblVar.zza;
        zzikp zzikpVar9 = zzgblVar.zzj;
        zzggj zza12 = zzggj.zza(zza2, zzikpVar6, zza5, zzikpVar8, zza, zzikpVar9, zzikpVar7);
        this.zzm = zza12;
        zzggv zza13 = zzggv.zza(zza2, zzikpVar6, zzikpVar8, zzikpVar7);
        this.zzn = zza13;
        zzggx zza14 = zzggx.zza(zza2, zzikpVar6, zza5, zzikpVar8, zzikpVar7);
        this.zzo = zza14;
        zzggh zza15 = zzggh.zza(zza2, zza5, zzikpVar9, zzikpVar7);
        this.zzp = zza15;
        zzikr zza16 = zziks.zza(11, 0);
        zza16.zza(zza3);
        zza16.zza(zza4);
        zza16.zza(zza6);
        zza16.zza(zza7);
        zza16.zza(zza8);
        zza16.zza(zza9);
        zza16.zza(zza11);
        zza16.zza(zza12);
        zza16.zza(zza13);
        zza16.zza(zza14);
        zza16.zza(zza15);
        zziks zzc2 = zza16.zzc();
        this.zzq = zzc2;
        zzikg zzc3 = zzikh.zzc(view);
        this.zzr = zzc3;
        zzikg zzc4 = zzikh.zzc(activity);
        this.zzs = zzc4;
        zzikp zzikpVar10 = zzgbrVar.zzb;
        zzikp zzikpVar11 = zzgblVar.zzu;
        zzggf zza17 = zzggf.zza(zza2, zzikpVar10, zzc3, zzc4, zzikpVar11);
        this.zzt = zza17;
        zzikp zza18 = zzikf.zza(zzgfd.zza(zza10));
        this.zzu = zza18;
        zzghh zza19 = zzghh.zza(zza2, zzikpVar10, zza18, zzc3, zzikpVar11);
        this.zzv = zza19;
        zzikr zza20 = zziks.zza(11, 0);
        zza20.zza(zza3);
        zza20.zza(zza4);
        zza20.zza(zza7);
        zza20.zza(zza17);
        zza20.zza(zza19);
        zza20.zza(zza8);
        zza20.zza(zza9);
        zza20.zza(zza11);
        zza20.zza(zza12);
        zza20.zza(zza13);
        zza20.zza(zza14);
        zziks zzc5 = zza20.zzc();
        this.zzw = zzc5;
        zzghf zza21 = zzghf.zza(zza2, zzgbrVar.zzb, zza5, zza18, zzgblVar.zzu);
        this.zzx = zza21;
        zzikr zza22 = zziks.zza(12, 0);
        zza22.zza(zza3);
        zza22.zza(zza4);
        zza22.zza(zza7);
        zza22.zza(zza17);
        zza22.zza(zza19);
        zza22.zza(zza8);
        zza22.zza(zza9);
        zza22.zza(zza11);
        zza22.zza(zza12);
        zza22.zza(zza13);
        zza22.zza(zza14);
        zza22.zza(zza21);
        zziks zzc6 = zza22.zzc();
        this.zzy = zzc6;
        this.zzz = zzikf.zza(zzgfa.zza(zzgblVar.zzx, zzgblVar.zzG, zzgbrVar.zzb, zza, zzc, zza2, zzc2, zzc5, zzc6, zzgblVar.zzu));
    }

    @Override // com.google.android.gms.internal.ads.zzgfc
    public final zzgez zza() {
        return (zzgez) this.zzz.zzb();
    }
}
